   "source": [
    "#Import CSV file\n",
    "import pandas as pd\n",
    "\n",
    "#User Input for kW/ton and kW/Hr Cost\n",
    "kw_ton = float(input(\"Chiller Efficiency in kW/ton? \"))\n",
    "kwhr_cost = float(input(\"Cost of kW/Hr? \"))\n",
    "\n",
    "#Define Cooling Load Function\n",
    "def cooling_load(CFM, supply_temp, return_temp):\n",
    "    delta_t = return_temp - supply_temp\n",
    "    BtuH = CFM * delta_t * 1.085\n",
    "    tons = BtuH / 12000\n",
    "    return BtuH, tons\n",
    "#a typical chiller runs around 0.6-1.2 kW/ton) and a $/kWh rate (around $0.12 is realistic).\n",
    "def summarize_loads(rooms):\n",
    "    results = []\n",
    "    \n",
    "    for room in rooms:\n",
    "        btu, tons = cooling_load(room[\"cfm\"],room[\"t_supply\"],room[\"t_return\"])\n",
    "        if room[\"cfm\"] < 1000:\n",
    "            print(\"WARNING\", room[\"name\"], \"is running under 1000 CFM\")\n",
    "            \n",
    "        #print(room[\"name\"], \"->\",(round(btu,2)) , \"BTU/hr,\",(round(tons,2)), \"tons\")\n",
    "        results.append({\n",
    "            \"name\" : room[\"name\"],\n",
    "            \"btu\" : btu,\n",
    "            \"tons\" : tons,\n",
    "        })\n",
    "\n",
    "    total_BtuH = sum(r[\"btu\"] for r in results)\n",
    "    total_tons = total_BtuH/12000\n",
    "\n",
    "    #Cost Calculator\n",
    "    total_kW = kw_ton * total_tons\n",
    "    monthly_cost = total_kW * kwhr_cost * 30 * 24\n",
    "\n",
    "    #Calculate percent of total code\n",
    "    for r in results:\n",
    "        percent = (r[\"btu\"]/total_BtuH) * 100\n",
    "        r[\"percent\"] = percent\n",
    "        #print(r[\"name\"],\":\", round(percent,2),\"% of total load\")\n",
    "        if r[\"tons\"] > 12:\n",
    "            print(\"WARNING\",r[\"name\"],\"EXCEEDS 12 TONS!!\")\n",
    "   \n",
    "    #Print all values\n",
    "    #print(\"Total BTU/hr:\", round(total_BtuH, 2))\n",
    "    #print(\"Total Tons:\", round(total_tons, 2))\n",
    "    #print(\"Total kW:\", round(total_kW, 3))\n",
    "    #print(\"Monthly Cost:\",\"$\",round(monthly_cost, 2))\n",
    "    results.append({\n",
    "        \"name\": \"TOTAL\",\n",
    "        \"btu\": round(total_BtuH, 2),\n",
    "        \"tons\": round(total_tons, 2),\n",
    "        \"percent\": 100.0\n",
    "    })\n",
    "        # turn results into a dataframe\n",
    "    df_results = pd.DataFrame(results)\n",
    "    \n",
    "    # export to csv\n",
    "    df_results.to_csv(\"output.csv\", index=False)\n",
    "    \n",
    "    print(\"Results saved to output.csv\")\n",
    "    \n",
    "    return results, total_BtuH,total_tons\n",
    "import matplotlib.pyplot as plt\n",
    "names = [r[\"name\"] for r in results]\n",
    "tons_list = [r[\"tons\"] for r in results]\n",
    "\n",
    "plt.bar(names, tons_list)\n",
    "plt.title(\"Cooling Load by Room\")\n",
    "plt.xlabel(\"Room\")\n",
    "plt.ylabel(\"Tons\")\n",
    "plt.xticks(rotation=45)\n",
    "\n",
    "plt.show()\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    df = pd.read_csv(\"HVACroomsCSVpractice.csv\")\n",
    "    rooms = df.to_dict(orient=\"records\")\n",
    "    results, total_BtuH, total_tons = summarize_loads(rooms)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
